### ISSUE TITLE
Clarifications of the Disclaimer

### ISSUE THREAD

**Issue by Ryzener** [kevinlekiller/amdctl#19]
I'd like to use this tool but the disclaimer scares me:

> This software can damage your hardware, use at your own risk.

Is it to cover the author's back just in case, or is it a real risk?
Was any hardware damaged by this tool?
Are there any specific settings or any specific pieces of hardware that are known to be potentially damaging/vulnerable?

I have an AMD Ryzen 5 3500U CPU on my laptop. Anything I should be aware of with my CPU?

**Comment by kevinlekiller** [comment]
I've not damaged anything, it's just standard disclaimer on overclock software to protect the author(s) from liability.

**Comment by Ryzener** [comment]
Ok, thanks :)
