### ISSUE TITLE
A way to reset the CPU to default settings

### ISSUE THREAD

**Issue by 60percentCaffeine** [kevinlekiller/amdctl#21]
A way to restore default CPU frequency, voltage, etc. would be a really useful feature. I accidentally forgot to back up the defaults and now my notebook's power usage looks like this...
![my_pc_is_about_to_explode](https://user-images.githubusercontent.com/10227290/69072140-3b741400-0a3c-11ea-81bc-129072501ef3.png)

**EDIT**: I was able to reset my CPU frequency/voltage by unplugging my notebook and rebooting it. Rebooting while connected to power didn't work.

**Comment by kevinlekiller** [comment]
I don't think this is possible, since changing values overwrites whatever is already there.

I recommend dumping the default values to a file, then you can reference them later:

`sudo ./amdctl -g > amctl.txt`
