### ISSUE TITLE
ERROR: Could not open CPU for reading! Is the msr kernel module loaded?

### ISSUE THREAD

**Issue by EljoDev** [kevinlekiller/amdctl#26]
When I try to do something ex: `$ ./amdctl -g` :

`Voltage ID encodings: SVI (serial)`
`Detected CPU model 30h, from family 16h with 4 CPU cores.`
`ERROR: Could not open CPU for reading! Is the msr kernel module loaded?`

I have tryed  `modprobe msr` but noting

How do I solve this error ?

**Comment by kevinlekiller** [comment]
If you're running Linux >= 5.9 ; MSR is not available to userspace, see https://github.com/kevinlekiller/amdctl/pull/25

**Comment by kevinlekiller** [comment]
Also, you'd have to run amdctl as root (`sudo ./amctl`).
