### ISSUE TITLE
kernel version check ought be performed at runtime

### ISSUE THREAD

**Issue by dankamongmen** [kevinlekiller/amdctl#39]
Hey there, good stuff here with `amdctl`. I'd like to make some changes, and figured I'd run them by you before starting in on them:

* checking the kernel version at build time doesn't make much sense to me
* checking it at runtime makes a lot more sense
* checking it at runtime *if we have an actual failure* makes more sense still
* so far as i can tell, the tool generally needs be run as root; it could just set `allow_writes` itself
  * we can hide this behind a CLI option, or alternatively prohibit it via a CLI option

what do you think? if you agree, i can hack this up today.

**Comment by kevinlekiller** [comment]
Sounds good, PR's are always welcome. Thanks.
