### ISSUE TITLE
AMD Kabini doesn't pass /proc/cpuinfo sanity check

### ISSUE THREAD

**Issue by huell3** [kevinlekiller/amdctl#5]
Starting amdctl on an AMD 5350 fails, even before showing usage, as the check at the end of gathering info from /proc/cpuinfo enumerates as false, as this CPU indeed has a model number of zero(well, at least mine does).

to verify, I commented it's line 359-361 out and it shows somewhat okay info in the pstates dump.

**Comment by kevinlekiller** [comment]
That's interesting, I hadn't thought of that, I'll change the default to -1, thanks

**Comment by huell3** [comment]
Looks good, thank you.
