### ISSUE TITLE
`-n` option

### ISSUE THREAD

**Issue by sidorsett** [kevinlekiller/amdctl#56]
Hi,

I would like to create a pull request for setting NBP0/NBP1 VID on 14h family, but I don't quite understand what the current `-n` options is intended to do.

- In `parseOpts`, it is [accepted](https://github.com/kevinlekiller/amdctl/blob/a10ccd05faf86a92bb51d6d1bd5a2fba16329238/amdctl.c#L319) only for families 10h and 11h.
- `NB_VID_BITS` are defined for [15h](https://github.com/kevinlekiller/amdctl/blob/a10ccd05faf86a92bb51d6d1bd5a2fba16329238/amdctl.c#L240) and [16h](https://github.com/kevinlekiller/amdctl/blob/a10ccd05faf86a92bb51d6d1bd5a2fba16329238/amdctl.c#L245) families.
- But [`printNbStates`](https://github.com/kevinlekiller/amdctl/blob/a10ccd05faf86a92bb51d6d1bd5a2fba16329238/amdctl.c#L656) neither uses those registers for 10h/11h nor 15h/16h to read and display NB VIDs.

Is option `-n` is in use or is just a historical artifact?

I use `amdctl` in the following way to set VID for P states:
- `amdctl -p0 -vX`
- `amdctl -p1 -vY`

and would think of a similar syntax for NBP0 states:
- `amdctl -n0 -vX`
- `amdctl -n1 -vY`

Do you have any proposal on command options to use so that to define VIDs for NBP0 and NBP1 states?

Cheers!

**Comment by AYuusuke** [comment]
Hi @sidorsett 

I had similar doubts while implementing NB P-State/Voltage handling. Current approach:
```
-n    Set north bridge voltage id (vid) for next NB P-State transition.
-b    Set north bridge P-State (NbPst).
```

Usage examples:
- `amdctl -n23` Set voltage to all NB P-States: NBP0, NBP1 etc.;
- `amdctl -b1` Set NB low power state (NBP1 on systems with two NB P-States) to all CPU P-States;
- `amdctl -n23 -b0 -p2` Set NB high power state (NBP0 on systems with two NB P-States) with adjusted voltage to CPU P2

Source code is here https://github.com/AYuusuke/amdctl/tree/dev/opt-n-b
Backward compatible with existing `-n` use cases on 10h/11h. Does this info help you in your journey?
