### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by vinibali** [kevinlekiller/amdctl#6]
Hello Kevin,

I just recently updated the amdctl-git package in the AUR repository.
Are you planning to assign any kind of version number to the releases?
The final package is still called amdctl-git-unknown-1 :)

Best regards

**Comment by kevinlekiller** [comment]
I created a release here : https://github.com/kevinlekiller/amdctl/releases

Not sure if it helps, if it's not good, let me know.

**Comment by vinibali** [comment]
Great, you can close the issue.
